# Generated by Django 5.0.6 on 2024-06-08 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=20)),
                ('aktivna', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=20)),
                ('adresa', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cena', models.IntegerField()),
                ('kolicina', models.IntegerField()),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.kategorija')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prodazba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('kolicina', models.IntegerField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.klient')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.produkt')),
            ],
        ),
    ]
